name: Build and Commit

on:
    push:
        branches: [main]
        paths-ignore:
            - 'dist/**'
    pull_request:
        branches: [main]
        paths-ignore:
            - 'dist/**'

jobs:
    build-and-commit:
        runs-on: ubuntu-latest

        # Skip workflow if commit message contains [skip ci] or [ci skip]
        if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run: npm run lint

            - name: Build application
              run: npm run build

            - name: Check for build changes
              id: verify-changed-files
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Commit build artifacts
              if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"

                  # Add all build artifacts
                  git add dist/ 

                  # Check if there are changes to commit
                  if ! git diff --cached --exit-code; then
                    # Amend the last commit with build artifacts
                    git commit --amend --no-edit
                    
                    # Force push the amended commit
                    git push --force-with-lease origin ${{ github.ref_name }}
                  else
                    echo "No build artifacts to commit"
                  fi

            - name: Comment on PR (if applicable)
              if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '🔧 **Build artifacts updated**\n\nThe build process has generated updated artifacts. Please review the changes in the `dist/` directory.'
                      })
